backend:
    name: git-gateway
    branch: main

# Media configuration
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

# Collections configuration
collections:
    - name: "facts"
      label: "Fun Facts"
      folder: "src/content"
      format: "json"
      identifier_field: "id"
      files:
          - file: "src/content/facts.json"
            name: "facts"
            label: "Fun Facts"
            fields:
                - label: "Facts"
                  name: "facts"
                  widget: "list"
                  fields:
                      - { label: "ID", name: "id", widget: "uuid" }
                      - { label: "Fact Text", name: "text", widget: "text" }

    - name: "jokes"
      label: "Jokes"
      folder: "src/content"
      format: "json"
      identifier_field: "id"
      files:
          - file: "src/content/jokes.json"
            name: "jokes"
            label: "Jokes Collection"
            fields:
                - label: "Jokes"
                  name: "jokes"
                  widget: "list"
                  fields:
                      - { label: "ID", name: "id", widget: "number" }
                      - {
                            label: "Question",
                            name: "question",
                            widget: "string",
                        }
                      - { label: "Answer", name: "answer", widget: "string" }

    # - name: "outdoor"
    #   label: "Outdoor Activities"
    #   folder: "src/content"
    #   format: "json"
    #   identifier_field: "name"
    #   files:
    #       - file: "src/content/outdoor.json"
    #         name: "outdoor"
    #         label: "Outdoor Activities"
    #         fields:
    #             - label: "Activities"
    #               name: "activities"
    #               widget: "list"
    #               fields:
    #                   - {
    #                         label: "Activity Name",
    #                         name: "name",
    #                         widget: "string",
    #                     }
    #                   - {
    #                         label: "Description",
    #                         name: "description",
    #                         widget: "string",
    #                     }
    #                   - {
    #                         label: "How to Play",
    #                         name: "howToPlay",
    #                         widget: "text",
    #                     }

    - name: "online_games"
      label: "Online Games"
      folder: "src/content"
      format: "json"
      files:
          - file: "src/content/online-games.json"
            name: "online_games"
            label: "Online Games"
            fields:
                - label: "Games"
                  name: "games"
                  widget: "list"
                  fields:
                      - { label: "Game Name", name: "name", widget: "string" }
                      - {
                            label: "Description",
                            name: "description",
                            widget: "string",
                        }
                      - { label: "URL", name: "url", widget: "string" }
                      - {
                            label: "Age Group",
                            name: "ageGroup",
                            widget: "string",
                        }
